export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const SUBMIT_ORDER = 'SUBMIT_ORDER';
export const EMPTY_CART = 'EMPTY_CART';
